name: Security Scan

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  development-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Security Scan [checkov + bandit] (development)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: development
  

  production-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Security Scan [checkov + bandit] (production)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: production

  staging-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Security Scan [checkov + bandit] (staging)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: staging
