name: Security Scan

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  development-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Terraform Plan and Checkov (development)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: development

  staging-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Terraform Plan and Checkov (staging)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: staging

  production-scan:
    if: startsWith(github.head_ref, 'feature/')
    name: Terraform Plan and Checkov (production)
    uses: ./.github/workflows/security-scan-reusable.yml
    with:
      environment: production
